### ISSUE TITLE
Identify simple personas and recruit test users

### ISSUE THREAD

**Issue by jefflbrauer** [agilesix/va.gov-cms#11]
1. Translator 
2. Spanish-speaking CMS user - inputting spanish content into CMS. 
2. Content stakeholder - Wants to reviewing spanish content before going live
4. Content manager - Wants to monitor localization progress.

**Comment by kevwalsh** [comment]
Assumptions about the _Spanish content editor_ user
- proficient in Spanish, in order to carry out tasks associated with manually migrating translations into Drupal. 
- proficient enough in English, to understand the Drupal interface.
- have little or no Drupal experience, but may have some experience using other content management systems.

**Comment by kevwalsh** [comment]
Recruitment strategy: 
* Recruit people CivicActions/A6 employees who match the above attributes.
