### ISSUE TITLE
Initial Content Editor Research

### ISSUE THREAD

**Issue by jefflbrauer** [agilesix/va.gov-cms#12]
As a content strategist, drupal engineer and systems architect, I understand the needs of editors and content reviewer/publishers with respect to publishing Spanish version of content so that we may design and build a drupal publishing workflow to fulfill those needs.

**Comment by swirtSJW** [comment]
# User test #1: Athena

## Warm-Up Questions (10 minutes)

- How would you describe your comfort level in Spanish 

1. It is my second language.  
My parents speak it in the house.

- Do you have experience with content management systems?

1. Not much.  No Drupal history.



*Enable screenshare*

## First task: Translate a page from start to finish

For the next activity, I am going to ask you to share your screen. Imagine you've been tasked with translating an existing piece of content into Spanish.
Link: https://translate.google.ca/translate?hl=&sl=auto&tl=es&u=https%3A%2F%2Fva.gov%2Fpension%2Feligibility 

This is one of the most sought after Spanish language page about benefits.  

I'm going to share a link to a the CMS where we will be inputting this content. 
http://rfq.va.agile6.com/pension/eligibility

Please log in using [spanish-editor1] [spanish-editor2] and password drupal8

`(If they did not notice the Translate link:) Please click the Translate link`

**Notes**
1.  (looking for method to translate) Confusion over what the task is.
2. Thinking the translation should go into the wysiwig field
3. Content accidentally already present  - (pause while we deleted)
4. Chose to edit the english version rather than add spanish. [Issue to make sure to address in training]
5. Guided to add the spanish version.
6.  Copy and pasted title
7.  Hunted for translated copy,  google translated content did not show metadata. (lack of familiarity with drupal specific field)
8. Comparing text from google translate to map what goes where. [success]
9. Copy and pasting smoothly now.
10. Copy and pasting would have been smoother if user had two monitors as she is used to.  (currently on vacation with only a single screen laptop) [recommend adding recommendation for having two monitors.]
11. Trying to match content to where it belongs in the cms.   [success]
12. Google translated content is missing what should be links (Google bug, not cms bug)
13. Vocalized the difference between "Save this translation" and Save and continue editing" [success]
14. vocalized the purpose of "changed to" drop down and described what each should do.  [success]
15. Chose published and hit "save this translation"
16. Success.


## Second Task: Start second translation   

Please go to Link: /admin/content

I'd like you to try to find another page the health care eligibility page and start translating it.

Tell me how you would get started from here.

1. Described what "edit button should do" [accurate]
2. Described assumption that Translate link would translate the page but not certain of the language, assumed she could pick. [accurate]


## Follow-up Questions (2 minutes)

- Do you have any other thoughts you would like to share?

1. Confused on the context not so much the how to.
2. Pretty easy once she understood the context.

**Comment by swirtSJW** [comment]
# User test #2: Hayley

## Warm-Up Questions (10 minutes)

- How would you describe your comfort level in Spanish 

1. Advanced.  Conversational in spanish.  Conducted a lot of research in spanish.

- Do you have experience with content management systems?

1.  Used content management systems but not Drupal.



## First task: Translate a page from start to finish

For the next activity, I am going to ask you to share your screen. Imagine you've been tasked with translating an existing piece of content into Spanish.
Link: https://translate.google.ca/translate?hl=&sl=auto&tl=es&u=https%3A%2F%2Fva.gov%2Fpension%2Feligibility 

This is one of the most sought after Spanish language page about benefits.  

I'm going to share a link to a the CMS where we will be inputting this content. 
http://rfq.va.agile6.com/pension/eligibility

Please log in using [spanish-editor1] [spanish-editor2] and password drupal8

`(If they did not notice the Translate link:) Please click the Translate link`

**Notes**
1. I would click translate [success]
2. I see I can edit the english content [success]
3. The spanish is not translated yet but I can click and add it. [success]
4. I should delete the english and put the spanish in? [accurate]
5. I can't see the translated meta title [non-issues, data not in the provided translated content]
6. Knew the "red star" meant required field [accurate]
7. Began copy and pasting quite smoothly.
8. I can skip stuff that is blank?  [points to empty fields]
9.  [looking at the react message] Found it on the google source and pasted [accurate] [pointed to a need for a translation of the react widget error message]
10. Working on related links. [No link to paste because google translate does not  have it... but moved the text.]
11. Overall thoughts:

   -  "Seemed simple to me."  
   - "Was not hard."  
   - "Easy to copy and paste"  
   - "Headings were clear."

12. Event triggered date is confusing because it was in the past.    11/13 [an unrelated artifact of using an old copy of the production database]
13 Current state published confusing [issues with existing workflow, unrelated to multi-lingual.]
14 Identified the purpose of Save this translation and save and continue editing. [accurate]
15 Scared by unlock button.  "sounds like doomsday"
15 Confused that it is published and not draft by default. [A possible artifact of having someone else editing the translation prior, or an actual bug.]
16 Non translatable fields can only be changed on the original doc.  [bug: create ticket]
17. Tried to find field highlighted in red to see what the error related to. [bug: reference in bug ticket
18 Error prevented saving.   [Scenario finished]



## Second Task: Start second translation   

Please go to Link: /admin/content

I'd like you to try to find another page the health care eligibility page and start translating it.

Tell me how you would get started from here.

1.  Clicked immediately on "Translate"  link [success]


## Follow-up Questions (2 minutes)

- Do you have any other thoughts you would like to share?

1. One looks like a button, the other looks like a link  [on the admin/content disconnect between edit button and translate link]
2. Some of the workflow settings were confusing. [related to wokbench, draft, publish ... not related to translation and others that were bugs.  Issues were created.]
