### ISSUE TITLE
Make site publicly available

### ISSUE THREAD

**Issue by bderfer68** [agilesix/va.gov-cms#2]
AC:
- [x] Should be publicly available @ rfq.va.agilesix.com

**Comment by ElijahLynn** [comment]
This is done now and available at http://rfq.va.agile6.com (also made http://dev.rfq.va.agile6.com)

* I launched an Ubuntu 18.04 AMI in AWS
* Added developer public SSH keys from github.com/<user>.keys to `/home/ubuntu/.ssh/authorized_keys` file
* Followed local setup instructions https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/README.md, but used the `multilingual-tech-demo` branch in this repo instead of `master`. 
  * This included installing Docker and Lando
* Added a .lando.local.yml with the below for DNS to work with the Lando Proxy container:
```
proxy:
  appserver:
     - rfq.va.agile6.com
```
* Ignored .lando.local.yml in the `.git/info/exclude` file
* Setup DNS to point at AWS Cname

I also created a oneliner deploy script:

`ssh ubuntu@rfq.va.agile6.com "cd va.gov-cms; git pull; lando composer install; lando drush updatedb --yes; lando drush config:import --yes; lando drush cache:rebuild"`
