### ISSUE TITLE
Create user research discsussion guide

### ISSUE THREAD

**Issue by jefflbrauer** [agilesix/va.gov-cms#25]
As a user researcher, I have a short discussion guide to follow when conducting user research so that data elicited from research is consistent from participant to participant.

**Comment by kevwalsh** [comment]
# Conversation Guide for CMS translation workflow

## Moderator logistics

*In the Attendees section, make sure everyone except the participant is on mute*.

*In the Audio section, click the drop-down arrow and make sure "Play Entry/Exit Chimes" is unchecked*.

*Check your screensharing setup:* Be sure to close extraneous windows as needed.

**Set-up screen sharing (verify participant is using desktop version):
Please click Share in your Zoom, to make sure you're able to do that with us today.

If user is not able to screen share, verify that they are using the desktop application, not the browser. User may need to exit and re-join. Tell them to run and download the application when prompted, instead of clicking on the 'browser' option.

*When the participant is ready, begin the session with the following intro:*

## Intro (5 minutes)

Thanks for joining us today! My name is Kevin and I also have some colleagues on the line observing and taking notes. Today we're going to talk about adding Spanish translation content to Drupal, with two discrete tasks.

Before we start, I want to mention a few things:

- **This entire session should take about 20 minutes** I want to be sure not to keep you much longer, so I may occasionally prompt you with the next question or topic.
- **In this session, we want to hear your honest opinions.** So please talk out loud as you have thoughts about each task. We are not testing your ability. We just want to improve the website to better meet Veteran's needs. I will not be offended by any opinions you express, and I welcome your feedback.
- **Are you comfortable if I record my screen and audio as we talk today?** We use the recordings to confirm that we have captured your opinions accurately.

We'll start recording our session.

*Start recording.*

## Warm-Up Questions (10 minutes)

- How would you describe your comfort level in Spanish 
- Do you have experience with content management systems?
- Tell me more about that.

*Enable screenshare*

## First task: Translate a page from start to finish

For the next activity, I am going to ask you to share your screen. Imagine you've been tasked with translating an existing piece of content into Spanish.
Link: https://translate.google.ca/translate?hl=&sl=auto&tl=es&u=https%3A%2F%2Fva.gov%2Fpension%2Feligibility 

This is one of the most sought after Spanish language page about benefits.  

I'm going to share a link to a the CMS where we will be inputting this content. 
http://rfq.va.agile6.com/pension/eligibility

Please log in using [spanish-editor1] [spanish-editor2] and password drupal8

`(If they did not notice the Translate link:) Please click the Translate link`


## Second Task: Start second translation   

Please go to Link: /admin/content

I'd like you to try to find another page the health care eligibility page and start translating it.

Tell me how you would get started from here.

## Follow-up Questions (2 minutes)

- Do you have any other thoughts you would like to share?

- Or questions?

## Thank-You and Closing  (1 minutes)

We really appreciate you taking the time to share your thoughts with us today. Your feedback is so helpful to us as we continue to work on the site and make sure it really works or CMS editors.
