### ISSUE TITLE
User Research Synthesis

### ISSUE THREAD

**Issue by jefflbrauer** [agilesix/va.gov-cms#31]
Synthesize user research into key insights and opportunities 
Write prototype enhancement user stories

**Comment by kevwalsh** [comment]
## Participant 1:

### Task 1: Find place to input Spanish translation, and in put form
* **Insight:** People inputting translations need training in Drupal, including the nature of its structured content. **Action:** Write training materials, create a training epic for translators (#17)
* **Insight**: The translate tab was difficult to find.
**Action**: Add translate button to existing right sidebar view (#48)
* **Insight**: The translate tab led her to the edit English content instead of add Spanish.  **Action**: None--training will cover.  (#17)
* **Insight**: Source translation did not cover metadata (title and description), which made it impossible for her to input the content into fields. **Action**: See #43
* **Insight:** Side-by-side screens would help. **Action**: add two-monitor set up to suggested setup during training. (#17)

### Task 2: Get to translation screen from dashboard
* **Insight**: Basic dashboard made sense.  "Translate" button label was understood. **Action**: none. 

### Additional Information
* Explanation of the task was confusing
* Inputting content was generally easy

## Participant 2
### Task 1: Find place to input Spanish translation, and in put form
* **Insight**: Some fields are not translateable because they share the same value in English and Spanish (eg React load times).   When drupal is not properly configured, spanish content entry users seem able to edit the content that is not translateable, and that causes a bug when they go to save.   **Actions**. Remove all fields that are not translateable from the content from.  (see #33, #36, #39)
* **Insight**: Google Translate showed React error text.   **Actions:** 1) Improve translated content model documentation to include React error messages. 2) Make react widget translateable.  (#36)
* **Insight**: Content moderation field is a bit confusing. **Actions**: 1) Default content moderation state on Spanish add should be "Draft". 2) Translate tab for node should show the moderation state for each language 3) Issue #41 

### Task 2: 
* **Insight**: Easy to find the Translate button. But it should be a button. **Action** #42: Make it a button.

### Additional Information
* Easy, straightforward!
